
spring:
  test:
    database:
      replace: none
  config:
      import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    show-sql: true
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED}
      path: ${SPRING_H2_CONSOLE_PATH}
